[package]
name = "stator"
description = "Clearly manage state transitions using closures in Rust."
version = "0.1.1"
authors = ["Ryan Layne"]
license-file = "LICENSE"
repository = "https://github.com/flagoworld/stator"
